root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "./tmp/main"
  poll = true
  poll_interval = 1000 # check every 1 sec
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor", "uploads", "web"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"]
  kill_delay = "500ms"
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true